version: '3'

services:
  # Configuration for Hub+Proxy
  jupyterhub:
    build: jupyterhub
    container_name: jupyterhub_hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_JUPYTER_IMAGE: jupyterlab_img
      DOCKER_NETWORK_NAME: rt_default
      HUB_IP: jupyterhub_hub
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:jupyter.example.com"
  
  jupyterlab:
    build: jupyterlab
    image: jupyterlab_img
    command: echo

# volumes:
#   ...

# networks:
#   ...